### ISSUE TITLE
Tare

### ISSUE THREAD

**Issue by flc85** [bogde/HX711#71]
It's possible to use more than 1 tare?

**Comment by electrokean** [comment]
Not from the library.  But the tare is just a zero offset.
You can save your own offsets in your code and do the simple math (subtraction).

**Comment by flc85** [comment]
for more explication:

I put a container -> tare1
I put products in the container and it becomes too small.
I put another container over -> tare2

I'm a newbie with arduino some explications how to save the offsets.

**Comment by electrokean** [comment]
Sorry, but this isn't the place to teach general programming.
The library gives you weights in units - the tare "offset" is just a nominal weight that is a zero reference, which you can subtract from later weight readings to get the difference.

**Comment by flc85** [comment]
I understand thank you for your help

**Comment by flc85** [comment]
in the example:
 scale.set_scale(21680.f);
why .f ?

**Comment by electrokean** [comment]
It forces the constant to be floating point.  Not critical in this case, but good practice.

**Comment by electrokean** [comment]
For a little more info, see https://stackoverflow.com/questions/5026570/suffix-of-f-on-float-value

**Comment by flc85** [comment]
ok thanks for the information.
It's possible to limite the result of scale.get_units(10); at 2 decimal?

**Comment by flc85** [comment]
I put a container -> tare1 
scale.tare()
i read get_offset() and i put it in a variable T1
I put products in the container and it becomes too small.
I put another container over -> tare2
scale.tare()
i read get_offset() and i put it in a variable T2
i read the scale get.value and to know the weight of products:   ((get.scale value-(T1-T2))/set_scale)
It is correct?

**Comment by electrokean** [comment]
No, that doesn't make sense to me.

You use `scale.tare()` only once, and then used `scale.get_units()` to get the weight since tare.
I'm assuming you have called `scale.set_scale()` properly.

Proper way:
1. put on container
2. call `scale.tare()`
3. `scale.get_units()` gives you W0 - should be 0 (or very close)
4. put product in container
5. `scale.get_units()` gives you W1 - contents so far
6. put another container
7. `scale.get_units()` gives you W2 - and (W2 - W1) is weight of second container
8. add more product
9. `scale.get_units()` gives you W3 - which is total weight since tare
10. W3 - (W2 - W1) is total product weight

If you didn't do the tare then W0 wouldn't be 0, but you could just subtract W0 from total.

**Comment by flc85** [comment]
Good idea, thank you
